/**
 * scripts/seed-courts.ts
 * Seeds the courts table with:
 *  A) 30 real iconic NYC public basketball courts
 *  B) 18 real NYC bookable indoor venues (coming soon)
 *
 * Usage:
 *   npm run seed:courts
 *
 * Required in .env.local:
 *   NEXT_PUBLIC_SUPABASE_URL
 *   SUPABASE_SERVICE_ROLE_KEY
 */

import path from 'path'
import { config } from 'dotenv'
import { createClient } from '@supabase/supabase-js'
import { getPhotoByName } from '../src/lib/court-photos'

config({ path: path.join(process.cwd(), '.env.local') })
config({ path: path.join(process.cwd(), '.env') })

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  console.error('❌  Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local')
  process.exit(1)
}

function point(lng: number, lat: number) {
  return `SRID=4326;POINT(${lng} ${lat})`
}

// ─── Section A: Public NYC Courts ────────────────────────────────────────────

const PUBLIC_COURTS = [
  {
    name: 'Rucker Park',
    address: '155th St & Frederick Douglass Blvd, New York, NY 10039',
    borough: 'manhattan',
    neighborhood: 'Harlem',
    lat: 40.8291,
    lng: -73.9365,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: true,
    rim_count: 3,
    num_courts: 3,
    amenities: ['water_fountain', 'bleachers'],
    description: 'The most famous streetball court in the world. Home of the Entertainment Basketball Classic (EBC) every summer, Rucker Park has hosted legends from Wilt Chamberlain to Kevin Durant. Located in Harlem\'s Polo Grounds neighborhood, it remains the epicenter of NYC streetball culture.',
  },
  {
    name: 'The Cage — West 4th Street Courts',
    address: '199 W 4th St, New York, NY 10014',
    borough: 'manhattan',
    neighborhood: 'Greenwich Village',
    lat: 40.7328,
    lng: -73.9990,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: true,
    rim_count: 2,
    num_courts: 1,
    amenities: [],
    description: 'An iconic cage court in the heart of Greenwich Village, enclosed by chain-link fencing that gives it its name. One of the most competitive outdoor pickup games in NYC, drawing top-level players from across the city year-round. Attracts spectators who line the fence to watch.',
  },
  {
    name: 'Dyckman Park',
    address: 'Nagle Ave & Dyckman St, New York, NY 10040',
    borough: 'manhattan',
    neighborhood: 'Inwood',
    lat: 40.8670,
    lng: -73.9275,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: true,
    rim_count: 2,
    num_courts: 2,
    amenities: ['water_fountain', 'bleachers'],
    description: 'A legendary summer basketball mecca at the northern tip of Manhattan. The Dyckman Basketball Tournament — held every summer — draws NBA players, pro prospects, and the best streetball talent in the country. A serious court with a passionate local following.',
  },
  {
    name: 'Goat Park (98th Street)',
    address: 'Amsterdam Ave & W 98th St, New York, NY 10025',
    borough: 'manhattan',
    neighborhood: 'Upper West Side',
    lat: 40.7948,
    lng: -73.9690,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 2,
    num_courts: 2,
    amenities: [],
    description: 'Named in honor of Earl "The Goat" Manigault, a Harlem basketball legend who played in the 1960s. Manigault was known as one of the most gifted players never to make the NBA. This Upper West Side court carries his legacy and remains an active neighborhood pickup spot.',
  },
  {
    name: 'Tompkins Square Park',
    address: 'Ave A & E 7th St, New York, NY 10009',
    borough: 'manhattan',
    neighborhood: 'East Village',
    lat: 40.7264,
    lng: -73.9818,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 2,
    num_courts: 2,
    amenities: ['water_fountain', 'restroom'],
    description: 'Downtown Manhattan\'s go-to outdoor court in one of NYC\'s most vibrant parks. Competitive pickup runs on weekends with players of all skill levels. The park\'s open atmosphere draws a diverse crew of ballers from across the Lower East Side and East Village.',
  },
  {
    name: 'Hamilton Fish Park',
    address: '128 Pitt St, New York, NY 10002',
    borough: 'manhattan',
    neighborhood: 'Lower East Side',
    lat: 40.7199,
    lng: -73.9796,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: true,
    rim_count: 2,
    num_courts: 2,
    amenities: ['water_fountain', 'restroom'],
    description: 'A neighborhood staple on the Lower East Side featuring two courts with lights for evening games. Regularly busy with competitive local runs. The park complex includes a pool and recreation center, making it a true community anchor.',
  },
  {
    name: 'Jackie Robinson Park',
    address: 'Edgecombe Ave & W 150th St, New York, NY 10031',
    borough: 'manhattan',
    neighborhood: 'Harlem',
    lat: 40.8261,
    lng: -73.9414,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: true,
    rim_count: 2,
    num_courts: 2,
    amenities: ['water_fountain'],
    description: 'Historic Harlem court named after the baseball and civil rights pioneer. Situated in the Sugar Hill neighborhood, it draws a strong local community of hoopers. Regular pickup games with a mix of skill levels and a deep Harlem basketball tradition.',
  },
  {
    name: 'Jesse Owens Playground',
    address: '1501 Lexington Ave, New York, NY 10029',
    borough: 'manhattan',
    neighborhood: 'East Harlem',
    lat: 40.8004,
    lng: -73.9413,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: true,
    rim_count: 2,
    num_courts: 2,
    amenities: ['water_fountain'],
    description: 'East Harlem runs named for the legendary Olympic sprinter. Good rims and lights for evening games. A solid neighborhood court popular with East Harlem\'s basketball community, with runs drawing players of all levels.',
  },
  {
    name: 'Riverside Park (76th St)',
    address: 'Riverside Dr & W 76th St, New York, NY 10023',
    borough: 'manhattan',
    neighborhood: 'Upper West Side',
    lat: 40.7815,
    lng: -73.9855,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 3,
    num_courts: 3,
    amenities: ['water_fountain'],
    description: 'Three courts in scenic Riverside Park along the Hudson River. A beloved Upper West Side spot with stunning park surroundings. Popular with joggers-turned-hoopers and weekend pickup runs. No lights, so pack it up before sunset.',
  },
  {
    name: 'Colonel David Marcus Playground',
    address: 'W 133rd St & Amsterdam Ave, New York, NY 10027',
    borough: 'manhattan',
    neighborhood: 'Hamilton Heights',
    lat: 40.8159,
    lng: -73.9527,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 2,
    num_courts: 2,
    amenities: [],
    description: 'Hamilton Heights neighborhood court serving the community between Harlem and Washington Heights. Quiet but competitive, this court sees regular pickup action from local residents. Classic NYC asphalt courts with standard rims.',
  },
  // Brooklyn
  {
    name: 'Marcy Playground',
    address: 'Marcy Ave & Myrtle Ave, Brooklyn, NY 11206',
    borough: 'brooklyn',
    neighborhood: 'Bed-Stuy',
    lat: 40.6949,
    lng: -73.9491,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 2,
    num_courts: 2,
    amenities: [],
    description: 'The Marcy Houses courts in Bed-Stuy, made famous as the childhood home of Jay-Z. Serious competition and deep local pride on these asphalt courts. A pilgrimage spot for hip-hop and basketball fans alike. Expect competitive runs with Brooklyn\'s finest.',
  },
  {
    name: 'Rodney Park',
    address: 'Keap St & S 3rd St, Brooklyn, NY 11211',
    borough: 'brooklyn',
    neighborhood: 'Williamsburg',
    lat: 40.7082,
    lng: -73.9573,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 2,
    num_courts: 2,
    amenities: [],
    description: 'Competitive Williamsburg runs in a tight neighborhood court. A hidden gem that draws serious ballers from across North Brooklyn. The compact setting creates an intense, fast-paced game. Runs get going on evenings and weekends.',
  },
  {
    name: 'Lincoln Terrace Park',
    address: 'Buffalo Ave & Eastern Pkwy, Brooklyn, NY 11213',
    borough: 'brooklyn',
    neighborhood: 'Crown Heights',
    lat: 40.6694,
    lng: -73.9327,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: true,
    rim_count: 4,
    num_courts: 4,
    amenities: ['water_fountain'],
    description: 'Historic Brooklyn hoops in Crown Heights. Four full courts with lights make this one of the best-equipped public courts in Brooklyn. The park has a long basketball tradition and draws strong competition. Lincoln Terrace hosted neighborhood legends for decades.',
  },
  {
    name: 'McCarren Park',
    address: 'Bedford Ave & N 12th St, Brooklyn, NY 11211',
    borough: 'brooklyn',
    neighborhood: 'Williamsburg/Greenpoint',
    lat: 40.7198,
    lng: -73.9513,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: true,
    rim_count: 4,
    num_courts: 4,
    amenities: ['water_fountain', 'restroom'],
    description: 'Popular North Brooklyn court drawing players from Williamsburg and Greenpoint. Multiple courts with lights make evening runs possible. The park\'s central location and good facilities make it a hub for North Brooklyn\'s growing basketball scene.',
  },
  {
    name: 'Maria Hernandez Park',
    address: 'Knickerbocker Ave & Starr St, Brooklyn, NY 11237',
    borough: 'brooklyn',
    neighborhood: 'Bushwick',
    lat: 40.7005,
    lng: -73.9218,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 2,
    num_courts: 2,
    amenities: [],
    description: 'Lively Bushwick neighborhood court serving the heart of Knickerbocker Ave. Good mix of skill levels with an active local community. A true neighborhood court that reflects Bushwick\'s diverse, close-knit basketball culture.',
  },
  {
    name: 'Commodore Barry Park',
    address: 'Navy St & Flushing Ave, Brooklyn, NY 11205',
    borough: 'brooklyn',
    neighborhood: 'Fort Greene',
    lat: 40.6987,
    lng: -73.9775,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 3,
    num_courts: 3,
    amenities: [],
    description: 'Navy Yard area court near the border of Fort Greene and DUMBO. A solid three-court setup that draws players from across North Brooklyn. Competitive runs in a tucked-away park that rewards those who know about it.',
  },
  {
    name: 'Tillary Park',
    address: 'Tillary St & Jay St, Brooklyn, NY 11201',
    borough: 'brooklyn',
    neighborhood: 'Downtown Brooklyn',
    lat: 40.6952,
    lng: -73.9867,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 2,
    num_courts: 2,
    amenities: [],
    description: 'Courts in the heart of Downtown Brooklyn, convenient to the subway and surrounded by the borough\'s commercial energy. A solid spot for quick lunchtime or after-work runs. Gets busy on weekday evenings with office workers and local residents.',
  },
  // Bronx
  {
    name: "St. Mary's Park",
    address: "St. Ann's Ave & E 145th St, Bronx, NY 10454",
    borough: 'bronx',
    neighborhood: 'Mott Haven',
    lat: 40.8086,
    lng: -73.9139,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 3,
    num_courts: 3,
    amenities: ['water_fountain'],
    description: 'Top Bronx court in Mott Haven with a rich tournament history. St. Mary\'s Park is where many Bronx legends cut their teeth. Serious competition in a neighborhood that takes basketball personally. Competitive runs every weekend throughout the spring and summer.',
  },
  {
    name: 'Orchard Beach Courts',
    address: 'Orchard Beach Rd, Bronx, NY 10464',
    borough: 'bronx',
    neighborhood: 'Pelham Bay',
    lat: 40.8648,
    lng: -73.7952,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 6,
    num_courts: 6,
    amenities: ['water_fountain', 'restroom', 'parking'],
    description: 'Six full courts by the beach — summertime basketball at its finest. Orchard Beach is the Bronx\'s Riviera and these courts see serious runs on summer weekends. Players come from across the borough and beyond for outdoor ball with ocean breezes. Parking available.',
  },
  {
    name: 'Crotona Park',
    address: 'Crotona Ave & E 173rd St, Bronx, NY 10457',
    borough: 'bronx',
    neighborhood: 'Tremont',
    lat: 40.8380,
    lng: -73.8951,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: true,
    rim_count: 4,
    num_courts: 4,
    amenities: ['water_fountain', 'restroom'],
    description: 'One of the Bronx\'s biggest parks with multiple courts and lights for evening play. Regular community tournaments and pickup games. Crotona\'s long history of basketball makes it a landmark for Bronx hoopers, drawing players from all corners of the borough.',
  },
  {
    name: 'Mullaly Park',
    address: 'E 164th St & River Ave, Bronx, NY 10452',
    borough: 'bronx',
    neighborhood: 'Highbridge',
    lat: 40.8280,
    lng: -73.9230,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: true,
    rim_count: 3,
    num_courts: 3,
    amenities: ['water_fountain'],
    description: 'Bronx court in the shadow of Yankee Stadium, less than a mile from the Grand Concourse. Good runs with Bronx players who are as competitive as they come. Lights make it a destination for after-work evening games throughout the summer season.',
  },
  {
    name: 'Franz Sigel Park',
    address: 'E 153rd St & Gerard Ave, Bronx, NY 10451',
    borough: 'bronx',
    neighborhood: 'Concourse',
    lat: 40.8255,
    lng: -73.9235,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 2,
    num_courts: 2,
    amenities: [],
    description: 'Classic Bronx neighborhood court near the Grand Concourse, minutes from Yankee Stadium. Competitive local runs in the heart of one of the Bronx\'s most storied neighborhoods. A go-to spot for Concourse-area hoopers.',
  },
  // Queens
  {
    name: 'Geraldine Ferraro Playground',
    address: '109-19 49th Ave, Corona, Queens, NY 11368',
    borough: 'queens',
    neighborhood: 'Corona',
    lat: 40.7426,
    lng: -73.9191,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: true,
    rim_count: 2,
    num_courts: 2,
    amenities: ['water_fountain'],
    description: 'Competitive Queens court in Corona with lights for evening games. A strong local pickup scene with players from all over Queens. The park draws serious competitors from the diverse surrounding neighborhood, making it one of Queens\' best public courts.',
  },
  {
    name: 'Roy Wilkins Park',
    address: 'Merrick Blvd & Baisley Blvd, Jamaica, Queens, NY 11434',
    borough: 'queens',
    neighborhood: 'Jamaica',
    lat: 40.6836,
    lng: -73.7646,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: true,
    rim_count: 4,
    num_courts: 4,
    amenities: ['water_fountain', 'restroom', 'parking'],
    description: 'Major Queens basketball hub in Southeast Queens. Four full courts with lights and ample parking. Roy Wilkins Park has been a basketball destination for Southeast Queens hoopers for generations, hosting community tournaments and attracting players from Jamaica, St. Albans, and beyond.',
  },
  {
    name: 'Lost Battalion Hall Rec Center',
    address: '93-29 Queens Blvd, Rego Park, Queens, NY 11374',
    borough: 'queens',
    neighborhood: 'Rego Park',
    lat: 40.7346,
    lng: -73.8564,
    surface_type: 'hardwood',
    indoor: true,
    has_lights: true,
    rim_count: 2,
    num_courts: 1,
    amenities: ['restroom', 'water_fountain'],
    description: 'One of Queens\' best indoor basketball facilities, run by NYC Parks. Hardwood surface in a proper gymnasium setting. Regularly scheduled pickup games and recreational leagues. A true Queens gem for hoopers who want a controlled indoor environment year-round.',
  },
  {
    name: 'Flushing Meadows Courts',
    address: 'Flushing Meadows Corona Park, Queens, NY 11368',
    borough: 'queens',
    neighborhood: 'Corona',
    lat: 40.7400,
    lng: -73.8408,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: true,
    rim_count: 6,
    num_courts: 6,
    amenities: ['water_fountain', 'restroom', 'parking'],
    description: 'Multiple courts in the iconic Flushing Meadows Corona Park — NYC\'s second-largest park. Popular with players from across Queens who come to ball in one of the borough\'s most beloved green spaces. Six courts with lights accommodate runs well into the evening.',
  },
  // Staten Island
  {
    name: 'Clove Lakes Park',
    address: '1150 Clove Rd, Staten Island, NY 10301',
    borough: 'staten_island',
    neighborhood: 'Sunnyside',
    lat: 40.6210,
    lng: -74.1105,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 2,
    num_courts: 2,
    amenities: ['water_fountain'],
    description: 'One of Staten Island\'s premier park courts, surrounded by the wooded beauty of Clove Lakes Park. Weekend runs draw local hoopers who enjoy the park setting. A peaceful contrast to the intensity of NYC street ball — same competitive spirit, different atmosphere.',
  },
  {
    name: 'Silver Lake Park',
    address: 'Victory Blvd, Staten Island, NY 10301',
    borough: 'staten_island',
    neighborhood: 'Sunnyside',
    lat: 40.6325,
    lng: -74.0947,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 2,
    num_courts: 2,
    amenities: [],
    description: 'Staten Island neighborhood court near the Silver Lake Reservoir. Active local scene with weekend warriors and neighborhood regulars. A solid outdoor spot for Staten Island\'s basketball community, convenient to multiple neighborhoods.',
  },
  {
    name: 'Lyons Pool & Courts',
    address: 'Victory Blvd & Bay St, Staten Island, NY 10301',
    borough: 'staten_island',
    neighborhood: 'Tompkinsville',
    lat: 40.6435,
    lng: -74.0770,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 2,
    num_courts: 2,
    amenities: ['water_fountain', 'restroom'],
    description: 'Courts adjacent to the Lyons Pool complex near the Staten Island Ferry. Active summer basketball scene with easy access from the ferry for those making the trip from Brooklyn or Manhattan. A starting point for discovering Staten Island ball.',
  },
  {
    name: 'PS 5 Playground',
    address: '820 Delafield Ave, Staten Island, NY 10310',
    borough: 'staten_island',
    neighborhood: 'Westerleigh',
    lat: 40.6218,
    lng: -74.1154,
    surface_type: 'asphalt',
    indoor: false,
    has_lights: false,
    rim_count: 2,
    num_courts: 2,
    amenities: [],
    description: 'Neighborhood court in Westerleigh serving the residential heart of mid-Staten Island. Regular weekend pickup games with a mix of ages and skill levels. A community court that reflects Staten Island\'s tight-knit neighborhood basketball culture.',
  },
]

// ─── Section B: Bookable Indoor Venues (Coming Soon) ─────────────────────────

const BOOKABLE_VENUES = [
  {
    name: 'Basketball City',
    address: '299 South St, Pier 36, New York, NY 10002',
    borough: 'manhattan',
    neighborhood: 'Lower East Side',
    lat: 40.7060,
    lng: -73.9940,
    hourly_rate: 30000,
    num_courts: 6,
    amenities: ['restroom', 'water_fountain', 'locker_room', 'parking', 'bleachers'],
    description: 'NYC\'s premier basketball facility on the East River waterfront at Pier 36. Six NBA-regulation hardwood courts with pro-level lighting, scoreboards, and sound. The go-to spot for corporate tournaments, leagues, and serious pickup. Coming soon for instant online booking.',
  },
  {
    name: 'Chelsea Piers Basketball',
    address: 'Pier 62, 23rd St & Hudson River, New York, NY 10011',
    borough: 'manhattan',
    neighborhood: 'Chelsea',
    lat: 40.7476,
    lng: -74.0067,
    hourly_rate: 35000,
    num_courts: 4,
    amenities: ['restroom', 'water_fountain', 'locker_room', 'parking', 'bleachers', 'vending'],
    description: 'World-class sports complex on the Hudson River waterfront. Full-size hardwood basketball courts with premium facilities including locker rooms, showers, and a stunning waterfront location. Part of the iconic Chelsea Piers Sports & Entertainment Complex.',
  },
  {
    name: 'Premier Sports NYC',
    address: '230 W 45th St, New York, NY 10036',
    borough: 'manhattan',
    neighborhood: 'Midtown West',
    lat: 40.7583,
    lng: -73.9877,
    hourly_rate: 25000,
    num_courts: 3,
    amenities: ['restroom', 'water_fountain', 'locker_room'],
    description: 'Indoor basketball courts in the heart of Midtown Manhattan. Three full-size courts with hardwood floors and professional lighting. Centrally located near Times Square, making it convenient for after-work runs and weekend leagues.',
  },
  {
    name: 'Baruch College Gym',
    address: '55 Lexington Ave, New York, NY 10010',
    borough: 'manhattan',
    neighborhood: 'Gramercy',
    lat: 40.7403,
    lng: -73.9837,
    hourly_rate: 15000,
    num_courts: 2,
    amenities: ['restroom', 'water_fountain', 'locker_room'],
    description: 'Full-service indoor basketball courts at Baruch College in Gramercy. Two hardwood courts in a proper college gym setting. Great option for organized pickup games, small leagues, and team practices in a convenient Midtown location.',
  },
  {
    name: 'Columbia University Dodge Fitness Center',
    address: '3030 Broadway, New York, NY 10027',
    borough: 'manhattan',
    neighborhood: 'Morningside Heights',
    lat: 40.8069,
    lng: -73.9626,
    hourly_rate: 18000,
    num_courts: 2,
    amenities: ['restroom', 'water_fountain', 'locker_room'],
    description: 'Hardwood courts at Columbia University\'s Dodge Fitness Center in Morningside Heights. Two courts in a classic collegiate gymnasium. Well-maintained facility with full amenities, conveniently located near Harlem and the Upper West Side.',
  },
  {
    name: 'Hoops Klub Brooklyn',
    address: '373 Wythe Ave, Brooklyn, NY 11249',
    borough: 'brooklyn',
    neighborhood: 'Williamsburg',
    lat: 40.7174,
    lng: -73.9638,
    hourly_rate: 18000,
    num_courts: 3,
    amenities: ['restroom', 'water_fountain', 'locker_room'],
    description: 'Brooklyn\'s premier pickup basketball destination in the heart of Williamsburg. Three full-size hardwood courts in a converted industrial space. The culture and vibe match Williamsburg\'s energy perfectly. Popular with competitive rec players and organized leagues.',
  },
  {
    name: 'Aviator Sports',
    address: '3159 Flatbush Ave, Brooklyn, NY 11234',
    borough: 'brooklyn',
    neighborhood: 'Marine Park',
    lat: 40.5890,
    lng: -73.9018,
    hourly_rate: 20000,
    num_courts: 4,
    amenities: ['restroom', 'water_fountain', 'locker_room', 'parking', 'bleachers'],
    description: 'Multi-sport complex at Floyd Bennett Field featuring multiple full-size basketball courts. Aviator Sports is one of Brooklyn\'s largest indoor sports facilities, offering hardwood courts with high ceilings and professional amenities. Ample parking and easy access from Marine Park.',
  },
  {
    name: 'YMCA Prospect Park',
    address: '357 9th St, Brooklyn, NY 11215',
    borough: 'brooklyn',
    neighborhood: 'Prospect Park',
    lat: 40.6670,
    lng: -73.9858,
    hourly_rate: 15000,
    num_courts: 2,
    amenities: ['restroom', 'water_fountain', 'locker_room'],
    description: 'Full-service YMCA courts steps from Prospect Park in Park Slope. Two hardwood courts in a classic community facility. Great for structured pickup games and youth leagues. YMCA membership or court rental provides access to full locker rooms and amenities.',
  },
  {
    name: 'LIU Brooklyn Athletic Center',
    address: '1 University Plaza, Brooklyn, NY 11201',
    borough: 'brooklyn',
    neighborhood: 'Downtown Brooklyn',
    lat: 40.6897,
    lng: -73.9855,
    hourly_rate: 16000,
    num_courts: 2,
    amenities: ['restroom', 'water_fountain', 'locker_room', 'bleachers'],
    description: 'LIU Brooklyn\'s on-campus athletic center in Downtown Brooklyn. Full-size college basketball courts with bleachers and professional facilities. Centrally located near the Atlantic Terminal transit hub, making it one of the most accessible indoor courts in Brooklyn.',
  },
  {
    name: 'St. Francis College Gym',
    address: '180 Remsen St, Brooklyn, NY 11201',
    borough: 'brooklyn',
    neighborhood: 'Downtown Brooklyn',
    lat: 40.6927,
    lng: -73.9896,
    hourly_rate: 14000,
    num_courts: 1,
    amenities: ['restroom', 'water_fountain', 'locker_room'],
    description: 'Hardwood court at St. Francis College in the heart of Brooklyn Heights. Classic college gym in a landmark Downtown Brooklyn location. Well-maintained court with full amenities, convenient to the subway and Brooklyn Bridge.',
  },
  {
    name: 'Artistic Sports Complex',
    address: '28-28 Steinway St, Astoria, Queens, NY 11103',
    borough: 'queens',
    neighborhood: 'Astoria',
    lat: 40.7715,
    lng: -73.9235,
    hourly_rate: 18000,
    num_courts: 3,
    amenities: ['restroom', 'water_fountain', 'locker_room', 'parking'],
    description: 'Queens\' top indoor basketball complex in Astoria. Three full-size hardwood courts in a spacious facility with high ceilings and professional lighting. Popular with organized leagues, team practices, and serious pickup games. Ample parking makes it a regional draw.',
  },
  {
    name: 'Vibe Fitness BQE',
    address: '32-73 Steinway St, Long Island City, Queens, NY 11103',
    borough: 'queens',
    neighborhood: 'Long Island City',
    lat: 40.7620,
    lng: -73.9213,
    hourly_rate: 14000,
    num_courts: 2,
    amenities: ['restroom', 'water_fountain', 'locker_room'],
    description: 'Modern fitness and basketball facility near the BQE in Long Island City. Two full-size hardwood courts in a contemporary gym setting. Convenient for Queens and Manhattan players, with easy subway access. Great for after-work games and weekend leagues.',
  },
  {
    name: 'Commonpoint Queens Forest Hills',
    address: '67-09 108th St, Forest Hills, Queens, NY 11375',
    borough: 'queens',
    neighborhood: 'Forest Hills',
    lat: 40.7218,
    lng: -73.8465,
    hourly_rate: 16000,
    num_courts: 2,
    amenities: ['restroom', 'water_fountain', 'locker_room'],
    description: 'Community center courts in Forest Hills with professional facilities. Two hardwood courts in a well-maintained community gym. Commonpoint Queens operates multiple Queens facilities, making this a trusted destination for organized basketball in the borough.',
  },
  {
    name: 'Commonpoint Sam Field Center',
    address: '58-20 Little Neck Pkwy, Little Neck, Queens, NY 11362',
    borough: 'queens',
    neighborhood: 'Little Neck',
    lat: 40.7551,
    lng: -73.7371,
    hourly_rate: 14000,
    num_courts: 2,
    amenities: ['restroom', 'water_fountain', 'locker_room', 'parking'],
    description: 'Northeast Queens basketball facility in the Sam Field Community Center. Two courts with full locker room facilities and parking. Serves the eastern Queens community in a modern facility. Popular with organized leagues and family recreational play.',
  },
  {
    name: 'Gauchos Gym',
    address: '3 Featherbed Ln, Bronx, NY 10452',
    borough: 'bronx',
    neighborhood: 'Mount Hope',
    lat: 40.8387,
    lng: -73.9183,
    hourly_rate: 12000,
    num_courts: 2,
    amenities: ['restroom', 'water_fountain', 'locker_room'],
    description: 'The Bronx\'s legendary Gauchos Gym, home of the AAU Gauchos program that has produced NBA talent for decades. Two hardwood courts steeped in basketball history. The gym has shaped some of the Bronx\'s finest players. A pilgrimage spot for Bronx basketball culture.',
  },
  {
    name: 'Riverdale YMCA',
    address: '5625 Arlington Ave, Bronx, NY 10471',
    borough: 'bronx',
    neighborhood: 'Riverdale',
    lat: 40.8935,
    lng: -73.9118,
    hourly_rate: 13000,
    num_courts: 2,
    amenities: ['restroom', 'water_fountain', 'locker_room'],
    description: 'Full-service YMCA in Riverdale offering indoor basketball courts with complete amenities. Two courts in a community facility that serves the northern Bronx. Great for organized pickup, leagues, and youth programs. Professional staff and well-maintained facilities.',
  },
  {
    name: 'College of Staten Island Gym',
    address: '2800 Victory Blvd, Staten Island, NY 10314',
    borough: 'staten_island',
    neighborhood: 'Willowbrook',
    lat: 40.6020,
    lng: -74.1505,
    hourly_rate: 12000,
    num_courts: 3,
    amenities: ['restroom', 'water_fountain', 'locker_room', 'parking', 'bleachers'],
    description: 'Staten Island\'s largest college gym on the CUNY College of Staten Island campus. Three full-size courts with bleachers in a proper collegiate setting. Ample campus parking and a spacious modern facility. The best indoor basketball option in Staten Island.',
  },
  {
    name: 'YMCA Staten Island',
    address: '1566 Victory Blvd, Staten Island, NY 10314',
    borough: 'staten_island',
    neighborhood: 'Castleton Corners',
    lat: 40.6152,
    lng: -74.1254,
    hourly_rate: 11000,
    num_courts: 1,
    amenities: ['restroom', 'water_fountain', 'locker_room'],
    description: 'Staten Island\'s community YMCA offering indoor basketball in a full-service facility. One hardwood court in a well-maintained gym environment. The YMCA\'s community-focused programs make it a welcoming destination for players of all ages and skill levels.',
  },
]

// ─── Seeding Logic ────────────────────────────────────────────────────────────

async function seed() {
  const supabase = createClient(SUPABASE_URL!, SERVICE_ROLE_KEY!)

  // Verify schema has the new columns
  const { error: schemaCheck } = await supabase
    .from('courts')
    .select('neighborhood, booking_status, num_courts')
    .limit(0)

  if (schemaCheck) {
    console.error('❌  Schema missing new columns. Apply migration 004_enhancements.sql first:')
    console.error('    Supabase Dashboard → SQL Editor → paste supabase/migrations/004_enhancements.sql → Run')
    process.exit(1)
  }

  let seeded = 0
  let failed = 0

  // ── Section A: Public Courts ──
  console.log(`\n📍 Seeding ${PUBLIC_COURTS.length} public NYC courts…`)

  for (const court of PUBLIC_COURTS) {
    const photo = getPhotoByName(court.name, court.indoor ? 'indoor' : 'outdoor')
    const { error } = await supabase.from('courts').upsert({
      name: court.name,
      type: 'public',
      address: court.address,
      borough: court.borough,
      neighborhood: court.neighborhood,
      lat: court.lat,
      lng: court.lng,
      location: point(court.lng, court.lat),
      surface_type: court.surface_type,
      indoor: court.indoor,
      has_lights: court.has_lights,
      rim_count: court.rim_count,
      num_courts: court.num_courts,
      photos: [photo],
      amenities: court.amenities,
      description: court.description,
      is_bookable: false,
      booking_status: 'active',
    }, { onConflict: 'name,borough', ignoreDuplicates: false })

    if (error) {
      console.error(`  ✗ ${court.name} — ${error.message}`)
      failed++
    } else {
      console.log(`  ✓ ${court.name} (${court.neighborhood})`)
      seeded++
    }
  }

  // ── Section B: Bookable Venues ──
  console.log(`\n🏢 Seeding ${BOOKABLE_VENUES.length} bookable indoor venues…`)

  for (const venue of BOOKABLE_VENUES) {
    const photo = getPhotoByName(venue.name, 'indoor')
    const { error } = await supabase.from('courts').upsert({
      name: venue.name,
      type: 'private',
      address: venue.address,
      borough: venue.borough,
      neighborhood: venue.neighborhood,
      lat: venue.lat,
      lng: venue.lng,
      location: point(venue.lng, venue.lat),
      surface_type: 'hardwood',
      indoor: true,
      has_lights: true,
      rim_count: 2,
      num_courts: venue.num_courts,
      photos: [photo],
      amenities: venue.amenities,
      description: venue.description,
      hourly_rate: venue.hourly_rate,
      is_bookable: true,
      booking_status: 'coming_soon',
    }, { onConflict: 'name,borough', ignoreDuplicates: false })

    if (error) {
      console.error(`  ✗ ${venue.name} — ${error.message}`)
      failed++
    } else {
      console.log(`  ✓ ${venue.name} (${venue.neighborhood}, ${venue.borough}) — $${(venue.hourly_rate / 100).toFixed(0)}/hr`)
      seeded++
    }
  }

  const total = PUBLIC_COURTS.length + BOOKABLE_VENUES.length
  console.log(`\n✅ Done. ${seeded}/${total} courts seeded. ${failed > 0 ? `${failed} failed.` : ''}`)
}

seed().catch((err: Error) => {
  console.error('❌  Seed failed:', err.message)
  process.exit(1)
})
